#!/usr/bin/env python3
"""
Zero-shot evaluation of the SAM-DD dataset with Hugging Face vision-language models.

This script loads PaLI/Gemma/LLaVA style checkpoints and prompts them to classify each
image into one of the dataset's 10 driver-behavior classes. Use it to sanity-check how
large VLMs perform before attempting any fine-tuning.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from PIL import Image

from DA.data_loader import CSVImageDataset, ImageFolderDataset
from VLM.models import VisionLanguageModel


DEFAULT_PROMPT = (
    "You are an expert on distracted driving behaviors. "
    "Given the photo of a driver, answer with exactly one label from the set: {label_list}. "
    "Respond using only the label id (for example: 0, 1, 2, ...)."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Classify images using a Hugging Face PaLI/LLaVA style model."
    )
    parser.add_argument(
        "--model-id",
        type=str,
        default="google/paligemma-3b-pt-224",
        help="Hugging Face repo id (e.g., google/paligemma-3b-pt-224 or llava-hf/llava-1.5-7b-hf).",
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        required=True,
        help="Root directory with Tester*/class/view folders or ImageFolder layout.",
    )
    parser.add_argument(
        "--labels-csv",
        type=Path,
        default=None,
        help="Optional CSV generated by build_samdd_labels.py.",
    )
    parser.add_argument(
        "--prompt-template",
        type=str,
        default=DEFAULT_PROMPT,
        help="Text template containing '{label_list}' placeholder.",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=16,
        help="Maximum tokens generated per sample.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.0,
        help="Sampling temperature (0.0 disables sampling).",
    )
    parser.add_argument(
        "--torch-dtype",
        type=str,
        default="bf16",
        help="Torch dtype override passed to the VLM loader (e.g., bf16, fp16, fp32).",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        help="Device spec passed to the VLM loader (default picks CUDA when available).",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional cap on the number of samples to score (useful for smoke tests).",
    )
    parser.add_argument(
        "--save-predictions",
        type=Path,
        default=None,
        help="Optional JSONL file containing detailed predictions.",
    )
    return parser.parse_args()


def _load_dataset(data_dir: Path, labels_csv: Path | None):
    dataset_kwargs = dict(transform=None)
    if labels_csv:
        dataset = CSVImageDataset(data_dir, labels_csv.expanduser().resolve(), **dataset_kwargs)
    else:
        dataset = ImageFolderDataset(data_dir, **dataset_kwargs)
    return dataset


def _format_label_list(classes: Sequence[str]) -> str:
    return ", ".join(f"{idx}:{name}" for idx, name in enumerate(classes))


def _label_lookup(classes: Sequence[str]) -> Dict[str, str]:
    lookup = {}
    for idx, cls in enumerate(classes):
        lookup[str(idx)] = cls
        lookup[cls.lower()] = cls
    return lookup


def _match_label(response: str, lookup: Dict[str, str]) -> str | None:
    cleaned = response.strip().lower()
    for candidate in lookup:
        if candidate in cleaned:
            return lookup[candidate]
    return None


def main() -> None:
    args = parse_args()
    data_dir = args.data_dir.expanduser().resolve()
    if not data_dir.exists():
        raise FileNotFoundError(f"Data directory '{data_dir}' not found.")

    dataset = _load_dataset(data_dir, args.labels_csv)
    classes = getattr(dataset, "classes", None)
    if not classes:
        raise RuntimeError("Dataset does not expose classes; ensure --labels-csv or ImageFolder layout.")

    vlm = VisionLanguageModel.from_pretrained(
        args.model_id,
        torch_dtype=args.torch_dtype,
        device=args.device,
    )

    lookup = _label_lookup(classes)
    samples: List[Tuple[Path, int]] = list(dataset.samples)
    if args.limit is not None:
        samples = samples[: args.limit]

    predictions = []
    correct = 0

    label_list = _format_label_list(classes)
    prompt = args.prompt_template.format(label_list=label_list)

    for idx, (path, target_idx) in enumerate(samples, start=1):
        with Image.open(path) as handle:
            image = handle.convert("RGB")
        response = vlm.generate(
            image,
            prompt,
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
        )
        pred_label = _match_label(response, lookup)
        target_label = classes[target_idx]
        is_correct = pred_label == target_label
        if is_correct:
            correct += 1

        predictions.append(
            {
                "index": idx - 1,
                "image": str(path),
                "target": target_label,
                "prediction": pred_label,
                "raw_response": response,
                "correct": is_correct,
            }
        )

        print(
            f"[{idx}/{len(samples)}] target={target_label} pred={pred_label} "
            f"match={is_correct} | response='{response}'"
        )

    accuracy = correct / len(samples) if samples else 0.0
    print(f"\nScored {len(samples)} samples | Accuracy={accuracy:.4f}")

    if args.save_predictions:
        args.save_predictions.parent.mkdir(parents=True, exist_ok=True)
        with args.save_predictions.open("w") as handle:
            for row in predictions:
                handle.write(json.dumps(row) + "\n")
        print(f"Saved detailed predictions to '{args.save_predictions}'.")


if __name__ == "__main__":
    main()
